### ISSUE TITLE
Create WP CLI command

### ISSUE THREAD

**Issue by Rahe** [keycdn/wp-optimus#1]
Hello!

To optimize large installation the admin page can be really problematic for optimizing all the images.
Can you create a WPCLI command for optimizing one/all attachments ?
Like using the `wp media regenerate` command, we can have a `wp media optimize` or a `wp optimus optimize` :)

**Comment by dramaturg** [comment]
Hi @Rahe,

we heard this request before so in the latest release (1.6.0) we added a `wp optimus optimize` command to help with bulk optimization.

Give it a try! :-)

**Comment by Rahe** [comment]
Great ! thank you very much I will try this soon :)
